# Generated by Django 2.1.1 on 2018-11-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_suggestive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlogin',
            name='userName',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='teacherlogin',
            name='userName',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
